### ISSUE TITLE
Closing the app RM2

### ISSUE THREAD

**Issue by karlossus** [khanhas/zshelf#2]
When I hit the top right X to close the app my RM2 hangs until I restart using the power button. Have tried pen and finger input and swiping back to launcher menu but only restarting works.

**Comment by khanhas** [comment]
How did you start zshelf? Do you use launcher?

**Comment by karlossus** [comment]
Yes, the launcher where on rm2 you have to swipe up at the sides of the screen

**Comment by khanhas** [comment]
Does it have a name?

**Comment by karlossus** [comment]
Apologies, I couldn’t find it. It’s remux.

**Comment by khanhas** [comment]
So I consulted remux's author and he said you should swipe up at screen side to open up launcher when you want to switch or close app.

**Comment by karlossus** [comment]
Ok, thank you. That does avoid having to restart the machine, so long as I don’t hit the top right X in zshelf. Can close, this is a workaround.
