### ISSUE TITLE
2.6+ Broken?

### ISSUE THREAD

**Issue by Servinjesus1** [khanhas/zshelf#5]
Possibly related to [toltec#322](https://github.com/toltec-dev/toltec/issues/322)

ZShelf has been blank since 2.6 (I had 2.6.2.75, now have 2.7.0.51). Any hope for an update?

**Comment by khanhas** [comment]
I'm quite busy with uni with and another project right now. I will see what i can do after this

**Comment by pr0fsmith** [comment]
Same issue.  I get the following when I try to launch from the commandline

root@reMarkable:~# LD_PRELOAD=/opt/lib/librm2fb_client.so.1.0.0 zshelf
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
EPD platform plugin loaded!
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[SERVER]  QProcess::Running
Creating window
[SERVER]  QProcess::Running
[SOCKET] "LIST" Connected
virtual void EPRenderContext::renderNextFrame(QSGRenderer*, uint) can't render without a renderer
Segmentation fault

**Comment by ralsei** [comment]
I can confirm that on an rM1, rebuilding the Toltec package with the `qt:v2.1` image makes ZShelf function perfectly fine.

**Comment by pr0fsmith** [comment]
Any plans to take a look at rM2?

Jun. 5, 2021 6:30:59 p.m. Hazel Levine ***@***.***>:

**Comment by pr0fsmith** [comment]
> I can confirm that on an rM1, rebuilding the Toltec package with the `qt:v2.1` image makes ZShelf function perfectly fine.

How did you do this? I want to try on my rM2

**Comment by ralsei** [comment]
If you download the artifacts from toltec-dev/toltec#366, you should be able to get a functioning version of zshelf without compiling it yourself.

**Comment by pr0fsmith** [comment]
Thanks.  I'm still new to github so do you mind explaining what you mean by
"artifacts" and what the installation process is?

**Comment by matteodelabre** [comment]
This issue seems to be a duplicate of #3 by the way.

**Comment by Servinjesus1** [comment]
Closed as duplicate of [#3](https://github.com/khanhas/zshelf/issues/3)
